yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/', views.add_comment,
         name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/users/urls.py
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [

    path(
        'signup/',
        views.SignUp.as_view(),
        name='signup'
    ),
    path(
        'login/',
        LoginView.as_view(
            template_name='users/login.html'
        ),
        name='login'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html'
        ),
        name='password_change_form'
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html'
        ),
        name='password_reset_form'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done'
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'
        ),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name='password_reset_complete'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
        ),
        name='password_change_done'
    ),
    path(
        'logout/',
        LogoutView.as_view(
            template_name='users/logged_out.html'
        ),
        name='logout'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),

]

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'
handler500 = 'core.views.internal_server_error'
handler501 = 'core.views.not_implemented'
handler502 = 'core.views.bad_gateway'
handler503 = 'core.views.service_unavailable'
handler504 = 'core.views.gateway_timeout'
handler505 = 'core.views.http_version_not_supported'
handler506 = 'core.views.variant_also_negotiates'
handler507 = 'core.views.insufficient_storage'
handler508 = 'core.views.loop_detected'
handler510 = 'core.views.not_extended'
handler511 = 'core.views.network_authentication_required'

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/templates/includes/csrf_check_body.html
{% load user_filters %}
{% csrf_token %}
{% for field in form %}
  <div class="form-group row my-3 p-3">
    <label for="{{ field.id_for_label }}">
      {{ field.label }}
      {% if field.field.required %}
        <span class="required text-danger">*</span>
      {% endif %}
    </label>
    {{ field|addclass:'form-control' }}
    {% if field.help_text %}
      <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
        {{ field.help_text|safe }}
      </small>
    {% endif %}
  </div>
{% endfor %}

yatube/templates/includes/errors.html
{% if form.errors %}
  {% for field in form %}
    {% for error in field.errors %}
      <div class="alert alert-danger">
        {{ error|escape }}
      </div>
    {% endfor %}
  {% endfor %}
  {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
      {{ error|escape }}
    </div>
  {% endfor %}
{% endif %}

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>
</footer>

yatube/templates/includes/header.html
{% load static %}
{% with request.resolver_match.view_name as view_name %}
  <header>
    <nav class="navbar navbar-expand-md navbar-light"
      style="background-color: lightskyblue">
      <div class="container-md">
        <a class="navbar-brand" href="{% url 'posts:index' %}">
          <img src="{% static 'img/logo.png' %}" width="30" height="30"
            class="d-inline-block align-top" alt="">
          <span style="color:red">Ya</span>tube
        </a>
        <button class="navbar-toggler" type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNavAltMarkup"
          aria-controls="navbarNavAltMarkup"
          aria-expanded="false"
          aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse"
          id="navbarNavAltMarkup">
          <ul class="nav nav-pills">
            <li class="nav-item">
              <a class="nav-link
                {% if view_name  == 'about:author' %}
                  active
                {% endif %}"
              href="{% url 'about:author' %}">Об авторе</a>
            </li>
            <li class="nav-item">
              <a class="nav-link
                {% if view_name  == 'about:tech' %}
                  active
                {% endif %}"
              href="{% url 'about:tech' %}">Технологии</a>
            </li>
            {% if user.username %}
              <li class="nav-item">
                <a class="nav-link
                  {% if view_name  == 'posts:post_create' %}
                    active
                  {% endif %}"
                href="{% url 'posts:post_create' %}">Новая запись</a>
              </li>
              <li class="nav-item">
                <a class="nav-link link-light
                  {% if view_name  == 'users:password_change_form' %}
                    active
                  {% endif %}"
                  href="{% url 'users:password_change_form' %}">
                    Изменить пароль
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link link-light"
                href="{% url 'users:logout' %}">Выйти</a>
              </li>
              <li>
                Пользователь: {{ user.username }}
              </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link link-light
                  {% if view_name  == 'users:login' %}
                    active
                  {% endif %}"
                href="{% url 'users:login' %}">Войти</a>
              </li>
              <li class="nav-item">
                <a class="nav-link link-light
                  {% if view_name  == 'users:signup' %}
                    active
                  {% endif %}"
                href="{% url 'users:signup' %}">Регистрация</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
  </header>
{% endwith %}

yatube/templates/includes/post_card.html
<ul>
  <li>
    Автор:
    <a href=
      "{% url 'posts:profile' post.author.username %}">
      {{ post.author.get_full_name }}
    </a>
  </li>
  <li>
    Дата публикации: {{ post.pub_date|date:"d E Y" }}
  </li>
</ul>
<p>
  {{ post.text }}
</p>