yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/', views.add_comment,
         name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),

]

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'
handler500 = 'core.views.internal_server_error'
handler501 = 'core.views.not_implemented'
handler502 = 'core.views.bad_gateway'
handler503 = 'core.views.service_unavailable'
handler504 = 'core.views.gateway_timeout'
handler505 = 'core.views.http_version_not_supported'
handler506 = 'core.views.variant_also_negotiates'
handler507 = 'core.views.insufficient_storage'
handler508 = 'core.views.loop_detected'
handler510 = 'core.views.not_extended'
handler511 = 'core.views.network_authentication_required'

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

from core.models import CreatedModel, PubDateModel

User = get_user_model()
TEXT_LIMIT: int = 15


class Post(PubDateModel):
    """Модель для постов автора."""
    text = models.TextField(
        'Текст',
        help_text='Введите текст поста'
    )

    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        'Group',
        models.SET_NULL,
        blank=True, null=True,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост'
    )

    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Публикацию'
        verbose_name_plural = 'Публикации'

    def __str__(self):
        return self.text[:TEXT_LIMIT]


class Group(models.Model):
    """Модель груп к которым относятся посты."""
    title = models.CharField(
        'Название',
        max_length=200
    )
    slug = models.SlugField(
        'Тег',
        max_length=100,
        unique=True
    )
    description = models.TextField(
        'Описание'
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Группу'
        verbose_name_plural = 'Группы'


class Comment(CreatedModel):
    """Модель для комментариев пользователей."""
    post = models.ForeignKey(
        'Post',
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Комментарий'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор'
    )
    text = models.TextField('Текст', help_text='Текст нового комментария')

    class Meta:
        ordering = ['-created']
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'


class Follow(models.Model):
    """Модель для подписок пользователей."""
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор',
    )

    class Meta:
        verbose_name = 'Подписчиков'
        verbose_name_plural = 'Подписчики'
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'], name='unique appversion')
        ]

    def __str__(self):
        return f'{self.user.username} -> {self.author.username}'

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')

    def clean_text(self):
        data = self.cleaned_data['text']
        if not data:
            raise forms.ValidationError('Поле не может быть пустым')
        return data


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        labels = {
            'text': 'Текст',
        }
        help_texts = {
            'text': 'Текст нового комментария',
        }

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page

from .forms import CommentForm, PostForm
from .models import Comment, Follow, Group, Post, User

NUMBER_OF_POSTS_PER_PAGE: int = 10


@cache_page(20)
def index(request):
    template = 'posts/index.html'
    post_list = Post.objects.select_related('author', 'group')
    paginator = Paginator(post_list, NUMBER_OF_POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.select_related('author', 'group')
    paginator = Paginator(post_list, NUMBER_OF_POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'group': group,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    user = User.objects.get(username=username)
    post_list = user.posts.select_related('author', 'group')
    paginator = Paginator(post_list, NUMBER_OF_POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    following = False
    if (request.user != user
            and request.user.is_authenticated
            and Follow.objects.filter(
                user=request.user,
                author=user,
            ).exists()):
        following = True
    context = {
        'username': user,
        'page_obj': page_obj,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    comments = Comment.objects.select_related('post', 'author')

    context = {
        'post': post,
        'form': form,
        'comments': comments,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(
        request.POST or None,
        files=request.FILES or None
    )
    if form.is_valid():
        post = form.save(commit=False)
        post.author_id = request.user.id
        user = request.user.username
        post.save()
        return redirect('posts:profile', user)

    context = {
        'form': form,
    }
    return render(request, 'posts/create_post.html', context)


def post_edit(request, post_id):
    is_edit = True
    post = get_object_or_404(Post, pk=post_id)

    if post.author != request.user:
        return redirect('posts:post_detail', post_id)

    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )

    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id)

    context = {
        'form': form,
        'is_edit': is_edit,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    comments = Comment.objects.select_related('author').filter(post=post)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
        return redirect('posts:post_detail', post_id=post_id)
    context = {
        'post': post,
        'form': form,
        'comments': comments,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def follow_index(request):
    posts_user = Post.objects.select_related('author').filter(
        author__following__user=request.user
    )
    paginator = Paginator(posts_user, NUMBER_OF_POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    if username != request.user.username:
        user = get_object_or_404(User, username=username)
        Follow.objects.get_or_create(user=request.user, author=user)

    return redirect("posts:profile", username=username)


@login_required
def profile_unfollow(request, username):
    get_object_or_404(
        Follow,
        author__username=username,
        user=request.user,
    ).delete()
    return redirect("posts:profile", username=username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
  {% if is_edit %}
    Редактировать запись
  {% else %}
    Добавить запись
  {% endif %}
{% endblock %}
{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            {% if is_edit %}
              Редактировать пост
            {% else %}
              Новый пост
            {% endif %}
          </div>
          <div class="card-body">
            {% if is_edit %}
              <form method="post" enctype ="multipart/form-data"
                action="{% url 'posts:post_edit' form.instance.pk %}">
            {% else %}
              <form method="post" enctype ="multipart/form-data"
                action="{% url 'posts:post_create' %}"
                >
            {% endif %}
            {% include 'includes/csrf_check_body.html' %}
            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
                {% if is_edit %}
                  Сохранить
                {% else %}
                  Добавить
                {% endif %}
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %}
  Авторы на которых вы подписаны.
{% endblock %}
{% block content %}
  <div class="container py-5">
    <h1>Авторы на которых вы подписаны</h1>
    {% include 'posts/includes/switcher.html' %}
      {% for post in page_obj %}
        {% include 'includes/post_card.html' %}
        {% if post.group %}
          <a href=
            "{% url 'posts:group_list' post.group.slug %}">
              {% include 'posts/includes/pictures.html' %}
              все записи группы
          </a>
        {% endif %}
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}
  {{ group.title }}
{% endblock %}
{% block content %}
  <div class="container py-5">
    <h1>{{ group.title }}</h1>
    <p>
      {{ group.description }}
    </p>
    <article>
      {% for post in page_obj %}
        {% include 'includes/post_card.html' %}
        {% include 'posts/includes/pictures.html' %}
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
      {% include 'posts/includes/paginator.html' %}
    </article>
  </div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}
  Это главная страница проекта Yatube
{% endblock %}
{% load thumbnail %}
{% block content %}
  <div class="container py-5">
    <h1>Последние обновления на сайте</h1>
    {% include 'posts/includes/switcher.html' %}
    <article>
      {% for post in page_obj %}
        {% include 'includes/post_card.html' %}
        {% if post.group %}
          <a href=
            "{% url 'posts:group_list' post.group.slug %}">
             {% include 'posts/includes/pictures.html' %}
              все записи группы
          </a>
        {% endif %}
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
      {% include 'posts/includes/paginator.html' %}
    </article>
    <hr>
  </div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}
  {{ post|truncatechars:30 }}
{% endblock %}
{% block content %}
{% load thumbnail %}
{% load user_filters %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
        {% if post.group %}
          <li class="list-group-item">
            Группа: {{ post.group.title }}
            <a href="{% url 'posts:group_list' post.group.slug %}">
              #{{ post.group.slug }}
            </a>
          </li>
        {% else %}
          <li class="list-group-item">
            Группа: без группы
          </li>
        {% endif %}
        <li class="list-group-item">
          Автор: {{ post.author.get_full_name }}
        </li>
        <li class="list-group-item d-flex
          justify-content-between align-items-center">
          Всего постов автора:
          <span >{{ post.author.posts.all.count }}</span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author.username %}">
            все посты пользователя
          </a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      {% include 'posts/includes/pictures.html' %}
      <p>
        {{ post.text }}
      </p>
      {% if user == post.author %}
        <a class="btn btn-primary"
          href="{% url 'posts:post_edit' post.pk %}">
          редактировать запись
        </a>
      {% endif %}
      {% if user.is_authenticated %}
        <div class="card my-4">
          <h5 class="card-header">Добавить комментарий:</h5>
          <div class="card-body">
            <form method="post" action="
              {% url 'posts:add_comment' post.id %}"
              >
              {% csrf_token %}      
              <div class="form-group mb-2">
                {{ form.text|addclass:"form-control" }}
              </div>
              <button type="submit" class="btn btn-primary">Отправить</button>
            </form>
          </div>
        </div>
      {% endif %}
      {% for comment in comments %}
        {% if post.pk == comment.post.pk %}
          <div class="media mb-4">
            <div class="media-body">
              <h5 class="mt-0">
                <a href="{% url 'posts:profile' comment.author.username %}">
                  {{ comment.author.username }}
                </a>
              </h5>
              <p>
                {{ comment.text }}
              </p>
            </div>
          </div>
        {% endif %}
      {% endfor %}
    </article>
  </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}
  Профайл пользователя
  {{ username.first_name }}
  {{ username.last_name }}
{% endblock %}
{% load thumbnail %}
{% block content %}
  <div class="container py-5">
    <div class="mb-5">
      <h1>
        Все посты пользователя
        {{ username.first_name }}
        {{ username.last_name }}
      </h1>
      <h3>Всего постов: {{ username.posts.all.count }} </h3>
      {% if following %}
      <a
        class="btn btn-lg btn-light"
        href="{% url 'posts:profile_unfollow' username.username %}"
        role="button"
      >
        Отписаться
      </a>
      {% else %}
        <a
          class="btn btn-lg btn-primary"
          href="{% url 'posts:profile_follow' username.username %}"
          role="button"
        >
          Подписаться
        </a>
      {% endif %}
      <article>
        {% for post in page_obj %}
          <ul>
            <li>
              Автор: {{ post.author.get_full_name }}
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>
          <p>
            {{ post.text }}
          </p>
          <a
            href="{% url 'posts:post_detail' post.pk %}">
              подробная информация
          </a><br><br>
          {% if post.group %}
            <a href=
              "{% url 'posts:group_list' post.group.slug %}">
                {% include 'posts/includes/pictures.html' %}
                #{{ post.group.slug }}
            </a>
          {% endif %}
          {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
        {% include 'posts/includes/paginator.html' %}
      </article>
    </div>
  </div>
{% endblock %}